# Generated by Django 5.0.2 on 2024-06-04 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('fifa_ranking', models.IntegerField()),
                ('fifa_points', models.DecimalField(decimal_places=1, max_digits=6)),
                ('short_name', models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.country')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('match_number', models.IntegerField()),
                ('stage', models.CharField(max_length=20)),
                ('home_away', models.BooleanField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.country')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.IntegerField()),
                ('score_2', models.IntegerField()),
                ('score_1_aet', models.IntegerField()),
                ('score_2_aet', models.IntegerField()),
                ('penalties_1', models.IntegerField()),
                ('penalties_2', models.IntegerField()),
                ('result', models.CharField(max_length=30)),
                ('match_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
