# Generated by Django 5.0.2 on 2024-06-04 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_away',
            field=models.CharField(max_length=20),
        ),
    ]
