# Generated by Django 5.0.2 on 2024-06-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_match_group_match_location_alter_match_home_away'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='country',
        ),
    ]
