# Generated by Django 4.2.4 on 2024-06-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_alter_score_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='country',
            field=models.ForeignKey(blank=True, default=211, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.country'),
        ),
    ]
