# Generated by Django 5.0.2 on 2024-06-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_alter_match_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.country'),
        ),
    ]
