# Generated by Django 5.0.2 on 2024-06-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_alter_match_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='penalties_1',
            new_name='penalties',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='penalties_2',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='score_1',
            new_name='score_aet',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='score_1_aet',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='score_2',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='score_2_aet',
        ),
    ]
