# Generated by Django 5.0.2 on 2024-06-05 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_alter_country_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.country'),
        ),
    ]
