# Generated by Django 4.2.10 on 2024-06-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_alter_prediction_penalties_alter_prediction_result_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='Score',
        ),
    ]
