# Generated by Django 4.2.10 on 2024-06-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0011_rename_match_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
    ]
