# Generated by Django 4.2.10 on 2024-06-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_match_alter_score_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='match_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.match'),
        ),
    ]
